name: ci
on: [push]

jobs:
  test:
    name: using go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24', '1.23', '1.22']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Lint & Test
        run: make setup-ci ci
