name: ci

on: [push]

jobs:
  test:
    name: using go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.26', '1.25']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Lint & Test
        run: make setup-ci ci
